# Generated by Django 5.1.1 on 2026-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coordinator',
            field=models.BooleanField(default=False, help_text='Admin role — can view all fields and monitor all agents.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_field_agent',
            field=models.BooleanField(default=False, help_text='Field agent role — can only see and update assigned fields.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
